In [2]:
#import dependencies
import os
import csv
import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt
import requests
from scipy import stats
from scipy.stats import linregress

In [3]:
happy2015_df = pd.read_csv('2015.csv')
happy2016_df = pd.read_csv('2016.csv')
happy2017_df = pd.read_csv('2017.csv')
happy2018_df = pd.read_csv('2018.csv')
happy2019_df = pd.read_csv('2019.csv')

In [4]:
#the survey changed over the years, so we need to clean the data up.
norm2015_df = happy2015_df.drop(['Region', 'Standard Error', 'Dystopia Residual'], axis=1)
norm2015_df = norm2015_df[['Country', 'Happiness Rank', 'Happiness Score', 'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)', 'Generosity']]
norm2015_df.columns = ["Country or Region", "Happiness Rank", "Happiness Score", "GDP per Capita", "Social Support", "Healthy Life Expectancy", "Freedom", "Trust", "Generosity"]

norm2016_df = happy2016_df.drop(['Region','Lower Confidence Interval', 'Upper Confidence Interval', 'Dystopia Residual'], axis=1)
norm2016_df = norm2016_df[['Country', 'Happiness Rank', 'Happiness Score', 'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)', 'Generosity']]
norm2016_df.columns = ["Country or Region", "Happiness Rank", "Happiness Score", "GDP per Capita", "Social Support", "Healthy Life Expectancy", "Freedom", "Trust", "Generosity"]

norm2017_df = happy2017_df.drop(['Whisker.high', 'Whisker.low', 'Dystopia.Residual'], axis=1)
norm2017_df = norm2017_df[['Country', 'Happiness.Rank', 'Happiness.Score', 'Economy..GDP.per.Capita.', 'Family', 'Health..Life.Expectancy.', 'Freedom', 'Trust..Government.Corruption.', 'Generosity']]
norm2017_df.columns = ["Country or Region", "Happiness Rank", "Happiness Score", "GDP per Capita", "Social Support", "Healthy Life Expectancy", "Freedom", "Trust", "Generosity"]

#norm2015_df = norm2015_df[['Country', 'Happiness Rank', 'Happiness Score', 'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)', 'Generosity']]

#happy2018_df.head()
norm2018_df = happy2018_df[['Country or region', 'Overall rank', 'Score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Perceptions of corruption', 'Generosity']]
norm2018_df.columns = ["Country or Region", "Happiness Rank", "Happiness Score", "GDP per Capita", "Social Support", "Healthy Life Expectancy", "Freedom", "Trust", "Generosity"]
#norm2018_df
norm2019_df = happy2019_df[['Country or region', 'Overall rank', 'Score', 'GDP per capita', 'Social support', 'Healthy life expectancy', 'Freedom to make life choices', 'Perceptions of corruption', 'Generosity']]
norm2019_df.columns = ["Country or Region", "Happiness Rank", "Happiness Score", "GDP per Capita", "Social Support", "Healthy Life Expectancy", "Freedom", "Trust", "Generosity"]
norm2019_df

,Country or Region,Happiness Rank,Happiness Score,GDP per Capita,Social Support,Healthy Life Expectancy,Freedom,Trust,Generosity
0,Finland,1,7.769,1.340,1.587,0.986,0.596,0.393,0.153
1,Denmark,2,7.600,1.383,1.573,0.996,0.592,0.410,0.252
2,Norway,3,7.554,1.488,1.582,1.028,0.603,0.341,0.271
3,Iceland,4,7.494,1.380,1.624,1.026,0.591,0.118,0.354
4,Netherlands,5,7.488,1.396,1.522,0.999,0.557,0.298,0.322
...,...,...,...,...,...,...,...,...,...
151,Rwanda,152,3.334,0.359,0.711,0.614,0.555,0.411,0.217
152,Tanzania,153,3.231,0.476,0.885,0.499,0.417,0.147,0.276
153,Afghanistan,154,3.203,0.350,0.517,0.361,0.000,0.025,0.158
154,Central African Republic,155,3.083,0.026,0.000,0.105,0.225,0.035,0.235
155,South Sudan,156,2.853,0.306,0.575,0.295,0.010,0.091,0.202

In [5]:
# Merge the first two datasets on "Country" so that no data is lost 
combined_df_2015_2016 = pd.merge(norm2015_df, norm2016_df, how='outer', on='Country or Region')
# Rename our _x columns to "2015"
combined_df_2015_2016 = combined_df_2015_2016.rename(columns={"Happiness Rank_x":"Happiness Rank 2015", 
                                                              "Happiness Score_x":"Happiness Score 2015", 
                                                              "GDP per Capita_x":"GDP 2015",
                                                              "Social Support_x": "Social Support 2015",
                                                              "Healthy Life Expectancy_x": "Life Expectancy 2015",
                                                              "Freedom_x": "Freedom 2015",
                                                              "Trust_x": "Trust 2015",
                                                              "Generosity_x": "Generosity 2015"
                                                             })

# Rename our _y columns to "2016"
combined_df_2015_2016 = combined_df_2015_2016.rename(columns={"Happiness Rank_y":"Happiness Rank 2016", 
                                                              "Happiness Score_y":"Happiness Score 2016", 
                                                              "GDP per Capita_y":"GDP 2016",
                                                              "Social Support_y": "Social Support 2016",
                                                              "Healthy Life Expectancy_y": "Life Expectancy 2016",
                                                              "Freedom_y": "Freedom 2016",
                                                              "Trust_y": "Trust 2016",
                                                              "Generosity_y": "Generosity 2016"
                                                             })

In [6]:
combined_df_2015_2016_2017 = pd.merge(combined_df_2015_2016, norm2017_df, how='outer', on='Country or Region')
combined_df_2015_2016_2017 = combined_df_2015_2016_2017.rename(columns={"Happiness Rank":"Happiness Rank 2017", 
                                                              "Happiness Score":"Happiness Score 2017", 
                                                              "GDP per Capita":"GDP 2017",
                                                              "Social Support": "Social Support 2017",
                                                              "Healthy Life Expectancy": "Life Expectancy 2017",
                                                              "Freedom": "Freedom 2017",
                                                              "Trust": "Trust 2017",
                                                              "Generosity": "Generosity 2017"
                                                             })

In [7]:
combined_df_2015_2016_2017_2018 = pd.merge(combined_df_2015_2016_2017, norm2018_df, how='outer', on='Country or Region')
combined_df_2015_2016_2017_2018 = combined_df_2015_2016_2017_2018.rename(columns={"Happiness Rank":"Happiness Rank 2018", 
                                                              "Happiness Score":"Happiness Score 2018", 
                                                              "GDP per Capita":"GDP 2018",
                                                              "Social Support": "Social Support 2018",
                                                              "Healthy Life Expectancy": "Life Expectancy 2018",
                                                              "Freedom": "Freedom 2018",
                                                              "Trust": "Trust 2018",
                                                              "Generosity": "Generosity 2018"
                                                             })

In [8]:
combined_df_all= pd.merge(combined_df_2015_2016_2017_2018, norm2019_df, how='outer', on='Country or Region')
combined_df_all = combined_df_all.rename(columns={"Happiness Rank":"Happiness Rank 2019", 
                                                              "Happiness Score":"Happiness Score 2019", 
                                                              "GDP per Capita":"GDP 2019",
                                                              "Social Support": "Social Support 2019",
                                                              "Healthy Life Expectancy": "Life Expectancy 2019",
                                                              "Freedom": "Freedom 2019",
                                                              "Trust": "Trust 2019",
                                                              "Generosity": "Generosity 2019"
                                                             })

combined_df_all = combined_df_all.fillna(0)

In [9]:
combined_df_all = combined_df_all.set_index("Country or Region")
combined_df_all.head()

,Happiness Rank 2015,Happiness Score 2015,GDP 2015,Social Support 2015,Life Expectancy 2015,Freedom 2015,Trust 2015,Generosity 2015,Happiness Rank 2016,Happiness Score 2016,...,Trust 2018,Generosity 2018,Happiness Rank 2019,Happiness Score 2019,GDP 2019,Social Support 2019,Life Expectancy 2019,Freedom 2019,Trust 2019,Generosity 2019
Country or Region,,,,,,,,,,,,,,,,,,,,,
Switzerland,1.0,7.587,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.0,7.509,...,0.357,0.256,6.0,7.480,1.452,1.526,1.052,0.572,0.343,0.263
Iceland,2.0,7.561,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,3.0,7.501,...,0.138,0.353,4.0,7.494,1.380,1.624,1.026,0.591,0.118,0.354
Denmark,3.0,7.527,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,1.0,7.526,...,0.408,0.284,2.0,7.600,1.383,1.573,0.996,0.592,0.410,0.252
Norway,4.0,7.522,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,4.0,7.498,...,0.340,0.286,3.0,7.554,1.488,1.582,1.028,0.603,0.341,0.271
Canada,5.0,7.427,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,6.0,7.404,...,0.291,0.321,9.0,7.278,1.365,1.505,1.039,0.584,0.308,0.285

In [12]:
new_df = combined_df_all[["Happiness Score 2015", "Happiness Score 2016", "Happiness Score 2017", "Happiness Score 2018", "Happiness Score 2019"]]
new_df

,Happiness Score 2015,Happiness Score 2016,Happiness Score 2017,Happiness Score 2018,Happiness Score 2019
Country or Region,,,,,
Switzerland,7.587,7.509,7.494,7.487,7.480
Iceland,7.561,7.501,7.504,7.495,7.494
Denmark,7.527,7.526,7.522,7.555,7.600
Norway,7.522,7.498,7.537,7.594,7.554
Canada,7.427,7.404,7.316,7.328,7.278
...,...,...,...,...,...
"Hong Kong S.A.R., China",0.000,0.000,5.472,0.000,0.000
Trinidad & Tobago,0.000,0.000,0.000,6.192,6.192
Northern Cyprus,0.000,0.000,0.000,5.835,5.718
North Macedonia,0.000,0.000,0.000,0.000,5.274
Gambia,0.000,0.000,0.000,0.000,4.516

In [13]:
transposed_rank = combined_df_all[["Happiness Rank 2015", "Happiness Rank 2016", "Happiness Rank 2017", "Happiness Rank 2018", "Happiness Rank 2019"]]
transposed_rank

,Happiness Rank 2015,Happiness Rank 2016,Happiness Rank 2017,Happiness Rank 2018,Happiness Rank 2019
Country or Region,,,,,
Switzerland,1.0,2.0,4.0,5.0,6.0
Iceland,2.0,3.0,3.0,4.0,4.0
Denmark,3.0,1.0,2.0,3.0,2.0
Norway,4.0,4.0,1.0,2.0,3.0
Canada,5.0,6.0,7.0,7.0,9.0
...,...,...,...,...,...
"Hong Kong S.A.R., China",0.0,0.0,71.0,0.0,0.0
Trinidad & Tobago,0.0,0.0,0.0,38.0,39.0
Northern Cyprus,0.0,0.0,0.0,58.0,64.0
North Macedonia,0.0,0.0,0.0,0.0,84.0
Gambia,0.0,0.0,0.0,0.0,120.0

In [14]:
new_df.mean()

Happiness Score 2015    4.996271
Happiness Score 2016    4.970606
Happiness Score 2017    4.881606
Happiness Score 2018    4.933194
Happiness Score 2019    4.961806
dtype: float64